table 'analytics fact_load'
	lineageTag: 24ba4bb1-0ca4-4c9c-bfc3-515ee718478f

	column loadsmart_id
		dataType: string
		lineageTag: 94e6713a-15e8-4cbc-b04d-211018473402
		summarizeBy: none
		sourceColumn: loadsmart_id

		annotation SummarizationSetBy = Automatic

	column shipper_id
		dataType: string
		lineageTag: e883b0b5-a782-4db4-b51e-3045a2d7531e
		summarizeBy: none
		sourceColumn: shipper_id

		annotation SummarizationSetBy = Automatic

	column carrier_id
		dataType: string
		lineageTag: 017f136b-4052-40a6-b97a-8123335ab29b
		summarizeBy: none
		sourceColumn: carrier_id

		annotation SummarizationSetBy = Automatic

	column lane_id
		dataType: string
		lineageTag: a52a75c0-62b2-432f-8977-a58b39510f3e
		summarizeBy: none
		sourceColumn: lane_id

		annotation SummarizationSetBy = Automatic

	column equipment_id
		dataType: string
		lineageTag: 80f329c9-509e-4967-a228-cc8dbe979994
		summarizeBy: none
		sourceColumn: equipment_id

		annotation SummarizationSetBy = Automatic

	column quote_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 02ad37be-087c-4bcd-b1c5-1aa8be096527
		summarizeBy: none
		sourceColumn: quote_date

		variation Variation
			isDefault
			relationship: 2346127f-8a56-473f-b173-b7bd7add6b8e
			defaultHierarchy: LocalDateTable_4ad5b92a-8bd5-4583-b27d-ca3fbbef7c26.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column book_date
		dataType: dateTime
		formatString: General Date
		lineageTag: f17dd877-688e-4c14-84af-cd5f858d24fe
		summarizeBy: none
		sourceColumn: book_date

		variation Variation
			isDefault
			relationship: 7b5a743a-bbe7-494f-8e14-9f5c087f5944
			defaultHierarchy: LocalDateTable_8c0e8a9a-dd1e-456d-98c3-0da17ccb4237.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column source_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 67c09655-ab76-4948-b2b9-225453956eea
		summarizeBy: none
		sourceColumn: source_date

		variation Variation
			isDefault
			relationship: c502a50a-d55b-4493-aac0-2e37d3a24831
			defaultHierarchy: LocalDateTable_2b4f2046-6ef7-4e65-82b5-dbf66e5d7b41.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column pickup_date
		dataType: dateTime
		formatString: General Date
		lineageTag: b0a535ff-2549-4dd9-92be-7851528db34c
		summarizeBy: none
		sourceColumn: pickup_date

		variation Variation
			isDefault
			relationship: c1a31ace-bf87-4773-8528-8e4755d2e636
			defaultHierarchy: LocalDateTable_52c8b973-d266-47f5-bbf8-2724200518da.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column delivery_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d5ec7ea4-a129-4a69-bcfe-eaa4b0491a5f
		summarizeBy: none
		sourceColumn: delivery_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column book_price
		dataType: double
		lineageTag: 4b23145c-7ea8-4aa8-bea5-a1814b9d6657
		summarizeBy: sum
		sourceColumn: book_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column source_price
		dataType: double
		lineageTag: 296c7514-b1d4-4e4c-9aad-16565a62f5c9
		summarizeBy: sum
		sourceColumn: source_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pnl_calculated
		dataType: double
		lineageTag: f4a4ab47-e549-4f2b-929e-1fbab81efcf8
		summarizeBy: sum
		sourceColumn: pnl_calculated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mileage
		dataType: double
		lineageTag: 7515f8e6-5cdf-492e-b889-61fbe80533b3
		summarizeBy: sum
		sourceColumn: mileage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sourcing_channel
		dataType: string
		lineageTag: e62c1221-a259-4a3a-908c-664385c88a46
		summarizeBy: none
		sourceColumn: sourcing_channel

		annotation SummarizationSetBy = Automatic

	column load_booked_autonomously
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 119e30a6-0fbd-41bb-b4b0-113c3d6671fc
		summarizeBy: none
		sourceColumn: load_booked_autonomously

		annotation SummarizationSetBy = Automatic

	column load_sourced_autonomously
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6f552785-78d6-4c3b-a2c0-fcb63ff41001
		summarizeBy: none
		sourceColumn: load_sourced_autonomously

		annotation SummarizationSetBy = Automatic

	column load_was_cancelled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 66fa09ec-1714-41f7-ba9c-d3f04a1164f5
		summarizeBy: none
		sourceColumn: load_was_cancelled

		annotation SummarizationSetBy = Automatic

	column is_delivered
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8811feed-47db-4556-909c-7429ae71da1d
		summarizeBy: none
		sourceColumn: is_delivered

		annotation SummarizationSetBy = Automatic

	column pnl_mismatch_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: dc862f00-1ed7-453c-9523-88420e217e19
		summarizeBy: none
		sourceColumn: pnl_mismatch_flag

		annotation SummarizationSetBy = Automatic

	column pnl
		dataType: double
		lineageTag: 5409c778-d290-4926-833d-4b23827e1dde
		summarizeBy: sum
		sourceColumn: pnl

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column book_price_per_mile
		dataType: double
		lineageTag: f12c408c-2294-494a-af55-97a3eb77b8b8
		summarizeBy: sum
		sourceColumn: book_price_per_mile

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column zero_book_price_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c093b03e-b0b7-48bb-8e67-3324de55d709
		summarizeBy: none
		sourceColumn: zero_book_price_flag

		annotation SummarizationSetBy = Automatic

	column zero_source_price_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ad388803-07f0-4a9b-843d-11ab21ccfa8a
		summarizeBy: none
		sourceColumn: zero_source_price_flag

		annotation SummarizationSetBy = Automatic

	column zero_pnl_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 666db507-2b1e-4e57-86e8-f6b62797eb03
		summarizeBy: none
		sourceColumn: zero_pnl_flag

		annotation SummarizationSetBy = Automatic

	column zero_mileage_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: aa5ce74f-4679-4991-a744-759247f80b3f
		summarizeBy: none
		sourceColumn: zero_mileage_flag

		annotation SummarizationSetBy = Automatic

	column mileage_imputed_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 78da24fb-fdb8-48b4-9ef5-de6c8347b688
		summarizeBy: none
		sourceColumn: mileage_imputed_flag

		annotation SummarizationSetBy = Automatic

	column mileage_unresolved_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5b475dd4-987f-4a0b-838b-da5a523be637
		summarizeBy: none
		sourceColumn: mileage_unresolved_flag

		annotation SummarizationSetBy = Automatic

	column cancelled_nonzero_price_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cd1d381c-411b-49ed-9594-892950d0894d
		summarizeBy: none
		sourceColumn: cancelled_nonzero_price_flag

		annotation SummarizationSetBy = Automatic

	column zero_price_active_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 27fc8731-ef48-48b6-b709-84f1f1280e15
		summarizeBy: none
		sourceColumn: zero_price_active_flag

		annotation SummarizationSetBy = Automatic

	column price_analysis_exclude_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 30499b8b-2e30-44d4-9e6a-fb39d2c68eba
		summarizeBy: none
		sourceColumn: price_analysis_exclude_flag

		annotation SummarizationSetBy = Automatic

	column book_price_outlier_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 608988c2-1606-47bc-8c24-bae151fcb974
		summarizeBy: none
		sourceColumn: book_price_outlier_flag

		annotation SummarizationSetBy = Automatic

	column source_price_outlier_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f1ce360c-0073-4669-8bf5-c0f45d26a714
		summarizeBy: none
		sourceColumn: source_price_outlier_flag

		annotation SummarizationSetBy = Automatic

	column pnl_outlier_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7f2b26b2-019a-4ae3-b9aa-f62421b883e6
		summarizeBy: none
		sourceColumn: pnl_outlier_flag

		annotation SummarizationSetBy = Automatic

	column zero_entry_count
		dataType: int64
		formatString: 0
		lineageTag: 097b9b99-bf1b-46c2-8559-d733b92c63cf
		summarizeBy: sum
		sourceColumn: zero_entry_count

		annotation SummarizationSetBy = Automatic

	partition 'analytics fact_load' = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("localhost", "loadsmart_dev"),
				    analytics_fact_load = Fonte{[Schema="analytics",Item="fact_load"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(analytics_fact_load,{{"delivery_date", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

