table 'analytics dim_date'
	lineageTag: 63494492-ac62-49bd-b8bb-b8577a4a8ab7

	column date_day
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5071bac3-de57-488f-b277-21b832d9f2c7
		summarizeBy: none
		sourceColumn: date_day

		variation Variation
			isDefault
			relationship: b10fbaa0-4fb5-48f2-89d1-ef5ea99015ab
			defaultHierarchy: LocalDateTable_8d87892d-0fda-4e0b-a911-1a6adb8f65ac.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: e3816676-2168-48df-8a58-325d5d8cef98
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column month
		dataType: int64
		lineageTag: ea1d3592-9c29-476d-a604-89bdcb3d5b89
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column year_month
		dataType: string
		lineageTag: 8943c582-5c6c-45dc-8d3a-ed516d137880
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: int64
		lineageTag: 3836ab3e-4191-474d-8a6e-e972e533355f
		summarizeBy: sum
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nome do Mês'
		dataType: string
		lineageTag: 6a315f4f-da9c-48b6-9967-251a0300311f
		summarizeBy: none
		sourceColumn: Nome do Mês
		sortByColumn: month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'analytics dim_date' = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("localhost", "loadsmart_dev"),
				    analytics_dim_date = Fonte{[Schema="analytics",Item="dim_date"]}[Data],
				    #"Nome do Mês Inserido" = Table.AddColumn(analytics_dim_date, "Nome do Mês", each Date.MonthName([date_day]), type text),
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Nome do Mês Inserido",{{"Nome do Mês", Text.Proper, type text}}),
				    #"Primeiros caracteres extraídos" = Table.TransformColumns(#"Colocar Cada Palavra Em Maiúscula", {{"Nome do Mês", each Text.Start(_, 3), type text}})
				in
				    #"Primeiros caracteres extraídos"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

